import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

MODELS_DIR = BASE_DIR / "models"
SAMPLE_DATA_DIR = BASE_DIR / "sample_data"
OUTPUTS_DIR = BASE_DIR / "outputs"
SCRIPTS_DIR = BASE_DIR / "scripts"
TESTS_DIR = BASE_DIR / "tests"

YOLO_MODEL_NAME = "yolo11n.pt"
YOLO_MODEL_PATH = MODELS_DIR / YOLO_MODEL_NAME

DEFAULT_CONFIDENCE_THRESHOLD = 0.25
DEFAULT_IOU_THRESHOLD = 0.45
DEVICE = "cpu"

ANNOTATED_IMAGE_NAME = "annotated_image.jpg"
ANNOTATED_IMAGE_PATH = OUTPUTS_DIR / ANNOTATED_IMAGE_NAME

BENCHMARK_REPORT_NAME = "benchmark_report.txt"
BENCHMARK_REPORT_PATH = OUTPUTS_DIR / BENCHMARK_REPORT_NAME

BENCHMARK_NUM_RUNS = 10

WEBCAM_INDEX = 0
WEBCAM_WIDTH = 1280
WEBCAM_HEIGHT = 720
WEBCAM_FPS_TARGET = 30
